name: Deploy to VPS.

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve secret repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/sao_paulo.pem
          du -h ~/sao_paulo.pem
          chmod 600 ~/sao_paulo.pem
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo ~/sao_paulo.pem

      - name: Connect to VPS instance
        run: |
          echo "connecting to ${{ vars.HOST_IP }}"
          sudo apt-get install sshpass
          sshpass -p "${{ secrets.ML_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -v -i ~/sao_paulo.pem mercadolivre@${{vars.HOST_IP}} << 'EOF'
            # Commands to run on the VPS instance
            echo "Connected to EC2 instance!"
            cd /home/mercadolivre/ml-fetcher
            git pull
            # Deploy Front End
            echo "Deploying FE"
            cd /home/mercadolivre/ml-fetcher/fe-react
            npm run build
            sudo cp -r build/* /var/www/mlsniper/
            EOF
